name: test-build

on:
    push:
        branches:
            - dev

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install -g gatsby-cli
            #- run: npm install -g flotiq-cli
            #- run: flotiq import . ${{ secrets.GATSBY_FLOTIQ_API_KEY }}
            - run: yarn install
            - run: gatsby build
              env:
                  GATSBY_FLOTIQ_API_KEY: ${{ secrets.GATSBY_FLOTIQ_API_KEY }}
                  SNIPCART_API_KEY: 'test'
                  GA_MEASUREMENT_ID: ''
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.ACCESS_TOKEN }}
                  publish_dir: ./public
